name: Upload to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Copy file to S3
        shell: bash
        env:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws_s3_bucket: aws-cloud-resume-challenge-karan-test1
          region: us-east-1
        run: |
          sudo apt-get update && sudo apt-get -y install awscli
          aws configure set aws_access_key_id $aws_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key 
          aws configure set default.region $region
          aws s3 cp ./ s3://$aws_s3_bucket/ --recursive --exclude ".git/*" --exclude ".github/*" --exclude ".gitignore"
          